Assignment2/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace Assignment2.ViewModels
{
    public class Login
    {


        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public bool RememberMe { get; set; }
	}

}

Assignment2/ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;


namespace Assignment2.ViewModels
{
	public class Register
	{
		[Required]
		public string FirstName { get; set; }
		[Required]
		public string LastName { get; set; }

        [Required]
        [StringLength(16, MinimumLength = 16, ErrorMessage = "Credit card number must be 16 digits")]
        public string CreditCard { get; set; }

        [Required]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Mobile number must be 10 digits")]
        public string MobileNo { get; set; }

        [Required]
		public string BillingAddress { get; set; }

		[Required]
		[RegularExpression(@"^[a-zA-Z0-9\s\.,#-]+$", ErrorMessage = "Allow all Special Characters")]
		public string ShippingAddress { get; set; }

		[Required]
		[DataType(DataType.EmailAddress)]
		[EmailAddress(ErrorMessage = "Invalid email address")]
		public string Email { get; set; }

		[Required]
		[DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^a-zA-Z\d]).{12,}$", ErrorMessage = "Password must be at least 12 characters long and include lowercase, uppercase, numbers, and special characters.")]
        public string Password { get; set; }

		[Required]
		[DataType(DataType.Password)]
		[Compare(nameof(Password), ErrorMessage = "Password and confirmation password do not match")]
		public string ConfirmPassword { get; set; }
	}
}

Assignment2/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Assignment2.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

Assignment2/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment2.Pages
{
	[Authorize]
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;

		public IndexModel(ILogger<IndexModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{

		}
	}
}

Assignment2/Pages/Login.cshtml.cs
using Assignment2.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace Assignment2.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public Login LModel { get; set; }

        private readonly SignInManager<IdentityUser> signInManager;

        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

		public async Task<IActionResult> OnPostAsync()
		{
			if (ModelState.IsValid)
			{
				var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password, LModel.RememberMe, false);
				if (identityResult.Succeeded)
				{
					//create the security context
					var claims = new List<Claim>
					{
						new Claim(ClaimTypes.Name, "c@c.com"),
						new Claim(ClaimTypes.Email, "c@c.com")
					};
					var i = new ClaimsIdentity(claims, "MyCookieAuth");
					ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(i);
					await HttpContext.SignInAsync("MyCookieAuth", claimsPrincipal);

					return RedirectToPage("Index");
				}
				ModelState.AddModelError("", "Username or Password incorrect");
			}
			return Page();
		}
	}
}

Assignment2/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment2.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;
        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }

        public async Task<IActionResult> OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

Assignment2/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment2.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

Assignment2/Pages/Register.cshtml.cs
using Assignment2.ViewModels;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment2.Pages
{
	//Initialize the build-in ASP.NET Identity
	public class RegisterModel : PageModel
	{
		private UserManager<IdentityUser> UserManager { get; }
		private SignInManager<IdentityUser> SignInManager { get; }
		[BindProperty]
		public Register RModel { get; set; }
		public RegisterModel(UserManager<IdentityUser> userManager,
		SignInManager<IdentityUser> signInManager)
		{
			this.UserManager = userManager;
			this.SignInManager = signInManager;
		}
		public void OnGet()
		{
		}
		//Save data into the database
		public async Task<IActionResult> OnPostAsync()
		{
			if (ModelState.IsValid)
			{
				var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
				var protector = dataProtectionProvider.CreateProtector("MySecretKey");
				var user = new IdentityUser()
				{
					UserName = RModel.Email,
					Email = RModel.Email,
				};
				var result = await UserManager.CreateAsync(user, RModel.Password);
				if (result.Succeeded)
				{
					await SignInManager.SignInAsync(user, false);
					return RedirectToPage("Index");
				}
				foreach (var error in result.Errors)
				{
					ModelState.AddModelError("", error.Description);
				}
			}
			return Page();
		}
	}
}

Assignment2/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div>
    @functions {
        public int divide(int x, int y)
        {
            string errormessage;
            try
            {
                return x / y;
            }
            catch (DivideByZeroException d)
            {
                errormessage = d.ToString();
                WriteLiteral("<br />Cannot Divide by Zero Exception found <br /><br />");
                WriteLiteral("Additional Info <br /><br />" + errormessage);
                return 0;
            }

        }
    }
    <h3>Division of 10 / 5 is @divide(10, 5)</h3>
    <h3>Division of 10 / 0 is @divide(12, 0)</h3>
</div>

Assignment2/Pages/Login.cshtml
@page
@model Assignment2.Pages.LoginModel
@{
}

<div class="container mt-5">


	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>
			<script src = "https://www.google.com/recaptcha/api.js"></script>




			<form method="post">

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="password" asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Login</button>
				</div>

				<div class="g-recaptcha" data-sitekey="6LcZUEwpAAAAAB1t4hkrcGDSxhbC8QXui5gGLNOt"></div>
			</form>
		</div>
	</div>
</div>

Assignment2/Pages/Logout.cshtml
@page
@model Assignment2.Pages.LogoutModel
@{
}

<form method="post">
    <div class ="container nt-5">
        <div class=" row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p>Are you sure you want to logout?</p>
                <p>
                    <button class="btn-outline-primary" asp-page-handler="Logout">Yes</button>
                    <button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
                </p>
            </div>
        </div>
    </div>
    
</form>

Assignment2/Pages/Register.cshtml
@page
@model Assignment2.Pages.RegisterModel
@{
}

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Register </h1>

			<form method="post">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.FirstName">First Name</label>
					<input type="Text" asp-for="RModel.FirstName" class="form-control" />
					<span asp-validaton-for="RModel.Firstname" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.LastName">Last Name</label>
					<input type="Text" asp-for="RModel.LastName" class="form-control" />
					<span asp-validaton-for="RModel.Lastname" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.CreditCard">Credit Card Number</label>
					<input type="number" asp-for="RModel.CreditCard" class="form-control" />
					<span asp-validaton-for="RModel.CreditCard" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.MobileNo">Mobile Number</label>
					<input type="number" asp-for="RModel.MobileNo" class="form-control" />
					<span asp-validaton-for="RModel.MobileNo" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.BillingAddress">Billing Address</label>
					<input type="Text" asp-for="RModel.BillingAddress" class="form-control" />
					<span asp-validaton-for="RModel.BillingAddress" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.ShippingAddress">Shipping Address</label>
					<input type="Text" asp-for="RModel.ShippingAddress" class="form-control" />
					<span asp-validaton-for="RModel.ShippingAddress" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Email">Email Address</label>
					<input type="Text" asp-for="RModel.Email" class="form-control" />
					<span asp-validaton-for="RModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Password">Password</label>
					<input type="password" asp-for="RModel.Password" class="form-control" />
					<span asp-validaton-for="RModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.ConfirmPassword">Confirm Password</label>
					<input type="password" asp-for="RModel.ConfirmPassword" class="form-control" />
					<span asp-validaton-for="RModel.ConfirmPassword" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Register</button>
				</div>
			</form>
		</div>
	</div>
</div>

Assignment2/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Assignment2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @{
                        if (SignInManager.IsSignedIn(User))
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                                </li>
                            </ul>

                            <ul class="navbar-nav d-flex justify-content-end">
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-area="" asp-page="/Logout">Logout</a>
                                </li>
                            </ul>
                        }
                        else
                        {
                            <ul class="navbar-nav d-flex justify-content-end flex-grow-1">
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-page="/Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-page="/Register">Register</a>
                                </li>
                            </ul>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Assignment2 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>